.prettierrc

This change adds a `.prettierrc` file to the project.
From looking at the existing code and #8, the current style seems to match `prettier` defaults except for `trailingComma` which is set to `"all"`. By specifying only that override, `prettier` will respect its default values for all other rules.
This allows `plugin:prettier/recommended` to know what to recommend, and prevents anyone with a global `.prettierrc` in their local env (like me 😁) from constantly overwriting the expected style.

chore(prettier): add .prettierrc file

---

.eslintrc.json
apps/nextjs/LinkLibrary.tsx
apps/nextjs/pages/_app.tsx
apps/storybook/.storybook/preview.js
apps/storybook/LinkLibrary.tsx
packages/components/src/components/LinkingProvider.tsx
packages/components/src/components/Links.tsx
packages/components/src/index.ts

Differences to proof-of-concept v2:
* [AnyProps](https://github.com/thunderstore-io/thunderstore-ui/commit/0035f47e436cd96538da8fb38f40a46e2ce04cc4#diff-cd76e2f9ce49485cabb251ae7796bb3f36a5ac6c773ac383159133fc999afa5fR41) uses `any` as suggested.
* Rather than use named `Output` type, use plain `ReactElement | null` instead ([example](https://github.com/thunderstore-io/thunderstore-ui/commit/0035f47e436cd96538da8fb38f40a46e2ce04cc4#diff-cd76e2f9ce49485cabb251ae7796bb3f36a5ac6c773ac383159133fc999afa5fR44)). I felt the `Output` unnecessary obfuscated the true return type in IDEs (at least VS Code).
* `Links.tsx` now uses a [wrapper function](https://github.com/thunderstore-io/thunderstore-ui/commit/e76c6dca461c889d365d9c0be46d680d88aa0d6f#diff-d6b620b573ded152e28a0407eadb68f4fdb64d09c52731b4 …

Implementation-agnostic linking for @thunderstore/components

---

apps/storybook/stories/components/PackageActions.stories.tsx

Story's content used a fixed date, which caused the human readable
output to wander from "2 months ago" to "3 months ago" and so on. This
triggered unnecessary and misleading need for a review in Chromatic.
The story now uses dynamic date, which causes the human readable
format to remain as "last week".

@thunderstore/storybook: fix wandering human readable date

---

packages/dapper/package.json

Build process failed due to errors in Dapper's package.json file:
* Add @babel/runtime required by preconstruct
* Move zod from devDependencies to dependencies
Refs TS-318

Fix Next.js app build process

---

apps/nextjs/components/SessionContext.tsx
apps/nextjs/hooks/useCompleteLogin.ts
apps/nextjs/pages/_app.tsx
apps/nextjs/utils/storage.ts

Implemented in earlier commits (in this repo and backend repo):
1. User clicks an authentication link
2. User's browser stores a "state token" to local storage (for CSRF
prevention) and redirects to OAuth provider's endpoint for login
3. After login, browser is redirected to client-side page, with query
parameters containing the state token (which is validated) and a
"code token"
4. Client-side page sends a request to Next.js API endpoint, which
creates another request containing the code token and a "shared
secret token" (for brute force prevention). For security reasons
the latter token is not available client-side, which is why this
sidestep is required
5. Next.js API endpoint sends the request to Django API endpoint
6. Django API endpoint validates the shared secret token
7. The …

WIP implementation for authentication, pt 5

---

packages/components/src/components/CommunityCard.tsx
packages/components/src/theme.ts

Initially only the name of the community and a chevron icon functioned
as an anchor element, now the whole card does. Therefore underlining
the community name on mouse hover didn't really work anymore - now the
hovered card has a slightly lighter border color to make it stand out.
Refs TS-388

@thunderstore/components: make whole CommunityCard clickable

---

packages/components/src/components/PackageCard.tsx

The image on a PackageCard component works as a link to the package's
detail page. The overlays, e.g. "pinned" tag is not clickable to avoid
confusion.
Refs TS-336

@thunderstore/components: make PackageCard image clickable

---

apps/nextjs/hooks/useFreshProps.ts
apps/nextjs/pages/_app.tsx
apps/nextjs/pages/c/[community]/p/[namespace]/[package]/index.tsx
packages/dapper/src/dapper.ts

Implemented in earlier commits (in this repo and backend repo):
1. User clicks an authentication link
2. User's browser stores a "state token" to local storage (for CSRF
prevention) and redirects to OAuth provider's endpoint for login
3. After login, browser is redirected to client-side page, with query
parameters containing the state token (which is validated) and a
"code token"
4. Client-side page sends a request to Next.js API endpoint, which
creates another request containing the code token and a "shared
secret token" (for brute force prevention). For security reasons
the latter token is not available client-side, which is why this
sidestep is required
5. Next.js API endpoint sends the request to Django API endpoint
6. Django API endpoint validates the shared secret token
7. The …

WIP implementation for authentication, pt 6

---

apps/nextjs/components/SessionContext.tsx
apps/nextjs/hooks/useFreshProps.ts

When user authenticates, the session id is stored in SessionProvider's
internal state for quick access and localStorage for retention. When
the session id is read from the localStorage, API backend is pinged to
check if the session is still valid.
Consumers of the SessionProvider context should check the provided
isSessionIdValidated flag before attempting to use the sessionId e.g.
in API calls.
Refs TS-230, TS-358

@thunderstore/nextjs: validate session id read from localStorage

---

apps/sertra/styles/globals.css

Reference TS-1064
Fixes the incorrect displaying of font-weights by declaring the `font-weight` range for `@font-face` -rules in `styles/globals.css`.

Sertra: Fix incorrect font-weight display issue

---

apps/sertra/components/mod-selector/button.tsx
apps/sertra/components/mod-selector/iconButton.tsx
apps/sertra/components/mod-selector/modal.module.css
apps/sertra/components/mod-selector/modal.tsx
apps/sertra/pages/create.tsx
apps/sertra/styles/SubmitServer.module.css

This PR just makes the modal a modal, and adds wrapper divs for the
form to ensure proper layout. There's much it could improve, especially
for component reusability (modals, buttons), but those are left outside
the scope to get the MVP done.

@thunderstore/sertra: make mod selection modal an actual modal

---

.github/workflows/test.yml

Disable the auto-deply workflow trigger, as it's not actively used for anything but generates noise in error reports in the infra repo.

Actions: Disable auto-deploy workflow

---

apps/cyberstorm-nextjs/dapper/client.tsx
apps/cyberstorm-nextjs/dapper/server.tsx
apps/cyberstorm-nextjs/package.json
apps/cyberstorm-storybook/.storybook/preview.js
apps/nextjs/pages/c/[communityIdentifier]/p/[namespace]/[packageName]/index.tsx
packages/cyberstorm/package.json
packages/cyberstorm/src/components/Layout/BaseLayout/PageHeader/PageHeader.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/Layout/PackageListLayout/PackageListLayout.tsx
packages/dapper/src/cyberstormMethods/community.ts
packages/dapper/src/cyberstormMethods/packageListings.ts
packages/dapper/src/cyberstormSchemas/community.ts
packages/dapper/src/dapper.ts
packages/dapper/src/implementations/dummy/DummyDapper.ts
packages/dapper/src/implementations/dummy/generate.ts
yarn.lock

Create a DummyDapper Dapper implementation and configure it for the cyberstorm-storybook and cyberstorm-nextjs. This is done to better separate the dummy code from the future production code, as opposed to mixing the two together.

CS: Create a DummyDapper implementation

---

.github/workflows/storybook-chromatic.yml

Disable chromatic snapshot builds for pushes that don't affect PRs

Disable unnecessary chromatic pushes

---

packages/cyberstorm/src/components/CopyButton/CopyButton.tsx

Navigator is not defined on server side, so any checks on its existence needs to be done within a useEffect hook to trigger it only on client side.
Refs TS-1778

@thunderstore/cyberstorm: fix SSR for CopyButton

---

apps/nextjs/package.json
packages/dapper/jest.config.js
packages/dapper/package.json
packages/thunderstore-api/.gitignore
packages/thunderstore-api/README.md
packages/thunderstore-api/jest.config.js
packages/thunderstore-api/package.json
packages/thunderstore-api/src/__tests__/index.ts
packages/thunderstore-api/src/index.ts
packages/thunderstore-api/tsconfig.json
yarn.lock

This is an alternative for https://github.com/thunderstore-io/thunderstore-ui/pull/774, addressing the feedback I provided there. The actual implementation is as simple as in the old PR to keep the PR small and get feedback early.
Also the changes target master branch rather than the existing WIP branch. The refactoring needs for the Dapper package seemed like a shapeless plop, and I was hard time deciding where to start from, so I decided to keep it simple and just replicate the old PR. The router changes from the WIP branch can be cherry picked later on top of these changes.

Add @thunderstore/thunderstore-api

---

apps/cyberstorm-nextjs/dapper/client.tsx
apps/cyberstorm-nextjs/dapper/server.tsx
apps/cyberstorm-nextjs/utils/cookie.ts
packages/dapper-ts/src/index.ts
packages/dapper-ts/src/methods/communities.ts
packages/dapper/src/dapper.ts
packages/thunderstore-api/src/index.ts

- RequestConfig defines information needed to request the content from the Thunderstore API. It's defined in the app and needs to be passed through the Dapper implementation all the way to to the package that handles the actual fetching
- @thunderstore/cyberstorm-nextjs uses DapperTs in the dapper providers
- @thunderstore/dapper remains unaware of the config being passed to DapperTs, so this doesn't affect e.g. DapperFake in any way
- @thunderstore/dapper-ts defines and implements an interface that augments the default Dapper interface by receiving the request config and storing it internally, to be eventually passed to thunderstore-api package
- @thunderstore/thunderstore-api defines the interface for the config so @thunderstore/dapper-ts depends on it but not the other way around
Refs …

@thunderstore/dapper-ts: handle passing down the config

---

apps/cyberstorm-storybook/stories/components/Switch.stories.tsx

Passing around defaultArgs was pointless since it only contained one optional prop and the value was set to component's default value.
Refs TS-1815

@thunderstore/cyberstorm-storybook: clean up Switch story file

---

apps/cyberstorm-storybook/stories/layouts/PackageListLayout.stories.tsx
packages/cyberstorm/src/components/Layout/CommunityProfileLayout/CommunityProfileLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/Layout/TeamProfileLayout/TeamProfileLayout.tsx
packages/dapper-fake/src/fakers/community.ts
packages/dapper-fake/src/fakers/utils.ts
packages/dapper-fake/src/index.ts
packages/dapper-ts/src/__tests__/index.ts
packages/dapper-ts/src/index.ts
packages/dapper-ts/src/methods/communities.ts
packages/dapper-ts/src/methods/communityFilters.ts
packages/dapper-ts/src/sharedSchemas.ts
packages/dapper/src/dapper.ts
packages/dapper/src/types/community.ts
packages/dapper/src/types/methods.ts
packages/thunderstore-api/src/fetch/__tests__/communityFilters.ts
packages/thunderstore-api/src/fetch/communityFilters.ts
packages/thunderstore-api/src/index.ts

@thunderstore/dapper: remove package categories from community details
Package categories, as well as package listing sections, which both
will be used for filtering packages, will be queried from a separate
endpoint in the future.
Refs TS-1885
@thunderstore/dapper: add getCommunityFilters method
Returns values that can be used to filter packages based on categories
and sections. Both categories and sections are always bound to a
specific community.
Refs TS-1885
@thunderstore/thunderstore-api: add fetchCommunityFilters
Refs TS-1885
@thunderstore/dapper-ts: add getCommunityFilters
Refs TS-1885

@thunderstore/dapper: add getCommunityFilters

---

apps/cyberstorm-storybook/stories/layouts/PackageListLayout.stories.tsx
packages/cyberstorm/package.json
packages/cyberstorm/src/components/Layout/CommunityProfileLayout/CommunityProfileLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/Layout/TeamProfileLayout/TeamProfileLayout.tsx
packages/cyberstorm/src/components/Layout/UserProfileLayout/UserProfileLayout.tsx
packages/cyberstorm/src/components/PackageList/PackageList.tsx
packages/cyberstorm/src/components/PackageSearch/FilterMenus/FilterMenu.module.css
packages/cyberstorm/src/components/PackageSearch/FilterMenus/SectionMenu.tsx
packages/cyberstorm/src/components/PackageSearch/PackageSearch.tsx
yarn.lock

SectioMenu allows filtering packages by section they belong to.
Sections are community specific. Common sections are "mods" and
"modpacks", but some communities don't use sections while others have
more than two.
Only one sections can be selected at a time, and if community has
sections, the first one is selected by default. This matches the
functionality of the old website while improving cacheability in
situations where e.g. "no section" and "mods" would mean the same
thing.
Refs TS-1860

@thunderstore/cyberstorm: add SectionMenu for PackageSearch

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/package.ts

[Refs - Missing discord and GitHub links under the package description](https://app.clickup.com/t/20413243/TS-1874)

Missing discord and GitHub links under the package description

---

apps/cyberstorm-nextjs/app/c/[community]/p/[namespace]/[package]/dependants/page.tsx
apps/cyberstorm-storybook/stories/components/PackageCard.stories.tsx
apps/cyberstorm-storybook/stories/layouts/PackageDependantsLayout.stories.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageTagList/PackageTagList.tsx
packages/cyberstorm/src/components/PackageCard/PackageCard.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/package.ts

PackagePreview, used to render package cards, should use the actual
values the backend will eventually return. By a decided convetion, the
naming should use backend terms to make it easier for developers to
work on both repositories.
Refs TS-1875

@thunderstore/dapper: make PackagePreview match the data from backend

---

packages/cyberstorm/src/components/Layout/HomeLayout/HomeLayout.tsx
packages/cyberstorm/src/components/PackageList/PackageList.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/methods.ts
packages/dapper/src/types/package.ts

In addition to the package information, extra information for
pagination purposes will be returned by the backend.
Refs TS-1875

@thunderstore/dapper: return package listings as paginated results

---

packages/cyberstorm/src/components/Layout/CommunityProfileLayout/CommunityProfileLayout.tsx
packages/cyberstorm/src/components/Layout/HomeLayout/HomeLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/Layout/TeamProfileLayout/TeamProfileLayout.tsx
packages/cyberstorm/src/components/Layout/UserProfileLayout/UserProfileLayout.tsx
packages/cyberstorm/src/components/PackageList/PackageList.tsx
packages/cyberstorm/src/components/PackageSearch/PackageSearch.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/index.ts
packages/dapper/src/types/methods.ts
packages/dapper/src/types/props.ts

@thunderstore/cyberstorm: remove unsupported props from PackageList
For the time being PackageList, and thus also PackageSearch, will
support only showing community or community+namespace scoped results.
Remove props that are meant for non-supported listings since they're
just adding noice currently. They can be readded if/when we add
related support to @thunderstore/dapper.
Refs TS-1875
@thunderstore/dapper: strongly type the scope of GetPackageListings
THe scope refers to the factors limiting the base result set when no
filters etc. are in play. E.g. the listing can be scoped to packages
listed in a specific community.
In attempt to be reusable, the earlier interface included a bunch of id
strings, e.g. community identifier and namespace name. All of these
were optional and there was no …

@thunderstore/dapper: augment GetPackageListings function signature

---

packages/cyberstorm/src/components/PackageList/PackageCount.tsx
packages/cyberstorm/src/components/PackageList/PackageList.tsx
packages/cyberstorm/src/components/PackageList/PackageOrder.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/methods.ts

@thunderstore/cyberstorm: change values used by PackageOrder component
The old values reflected backend implementation, which is none of the
UI's business. Use generic strings instead, so we don't have to change
the component if backend implementation changes.
Refs TS-1875
@thunderstore/dapper: rename GetPackageListings arguments
Use the names the backend expects for query parameters to avoid
renaming and confusion. Didn't want to force the UI to use the same
terms at this point, so the change only affects Dapper.
Refs TS-1875
@thunderstore/cyberstorm: fix edge cases on PackageCount display
- Show "No results" if no packages match filters
- Show "Showing X of X results" if the current page contains only one
package
- Show "Showing X-Y of Y results" if the current page doesn't contain
full …

Small fixes to Cyberstorm and Dapper

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageVersions/PackageVersions.module.css
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageVersions/PackageVersions.tsx

[Refs TS-1874 - Package - Versions tab missing alert](https://app.clickup.com/t/20413243/TS-1874)

Versions missing alert

---

apps/cyberstorm-nextjs/app/c/[community]/p/[namespace]/[package]/dependants/page.tsx
apps/cyberstorm-storybook/stories/components/PackageCard.stories.tsx
apps/cyberstorm-storybook/stories/layouts/PackageDependantsLayout.stories.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/PackageSearch/CategoryTagCloud/CategoryTagCloud.tsx
packages/cyberstorm/src/components/PackageSearch/FilterMenus/CategoryMenu.tsx
packages/dapper-fake/src/fakers/utils.ts
packages/dapper-ts/src/__tests__/index.ts
packages/dapper-ts/src/index.ts
packages/dapper-ts/src/methods/communities.ts
packages/dapper-ts/src/methods/communityFilters.ts
packages/dapper-ts/src/methods/currentUser.ts
packages/dapper-ts/src/methods/packageListings.ts
packages/dapper-ts/src/methods/team.ts
packages/dapper-ts/src/sharedSchemas.ts
packages/dapper-ts/src/utils.ts
packages/dapper/src/types/methods.ts
packages/dapper/src/types/props.ts
packages/dapper/src/types/shared.ts
packages/thunderstore-api/.gitignore
packages/thunderstore-api/package.json
packages/thunderstore-api/src/fetch/__tests__/communityPackageListings.ts
packages/thunderstore-api/src/fetch/__tests__/namespacePackageListings.ts
packages/thunderstore-api/src/fetch/__tests__/packageDependantsListings.ts
packages/thunderstore-api/src/fetch/communityPackageListings.ts
packages/thunderstore-api/src/fetch/namespacePackageListings.ts
packages/thunderstore-api/src/fetch/packageDependantsListings.ts
packages/thunderstore-api/src/index.ts
packages/thunderstore-api/src/types/index.ts
packages/thunderstore-api/types/package.json

Also contains changes from PRs #901, #902, #904, and #913, which couldn't be merged due to tests in the first PR getting outdated while waiting for the backend changes to get merged.

Use Dapper to fetch package dependants

---

apps/cyberstorm-nextjs/app/c/[community]/p/[namespace]/[package]/page.tsx
apps/cyberstorm-storybook/stories/layouts/PackageDetailLayout.stories.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyDialog/PackageDependencyDialog.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/index.ts
packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/package.ts

@thunderstore/cyberstorm: light cleanup for PackageDetailLayout
Reorder things for better readability.
Refs TS-1979
@thunderstore/cyberstorm: adjust PackageDetailLayout props
- Use the same prop names as the other layouts that accept the same
props, like PackageDependantsLayout
- Don't export the prop type since it's not necessary
- Remove managementDialogIsOpen prop from the layout. This was used to
control Storybook stories, but by and large makes little sense on a
layout component. Considered removing the prop from the Dialog
component altogether but decided to leave it for now to avoid scope
creep
- Remove the aforementioned Storybook story and cleanup the related
code
Refs TS-1979
@thunderstore/dapper: remove fields from Package interface
- Remove shortDescription somce backend only …

Prepare PackageDetailLayout for Dapper implementation

---

apps/cyberstorm-storybook/stories/components/MetaInfoItem.stories.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageMetaItems/PackageMetaItems.tsx
packages/cyberstorm/src/components/MetaInfoItem/MetaInfoItem.tsx
packages/cyberstorm/src/components/MetaInfoItemList/MetaInfoItemList.tsx
packages/cyberstorm/src/index.ts

@thunderstore/cyberstorm: clean up MetaInfoItem
Label was changed from optional to required prop, since having
labelless items makes little sense to me. Especially since it's a
required prop in MetaInfoList. In a pinch an empty string can be used,
but this forces the developer to make the decisions explicitly.
Other changes shouldn't affect functionality.
Refs TS-1975
@thunderstore/cyberstorm: clean up MetaInfoItemList
Change content prop's type to ReactNode to match the type expected by
MetaInfoItem. Otherwise shouldn't affect functionality.
Refs TS-1979
@thunderstore/cyberstorm: separate PackageMetaItems from layout
PackageDetailLayout has so much going on that splitting it to more
subcomponents improves the code quality.
Refs TS-1979

@thunderstore/cyberstorm: add PackageMetaItems

---

apps/cyberstorm-storybook/stories/components/NewTabs.stories.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/components/NewTabs/Tabs.module.css
packages/cyberstorm/src/components/NewTabs/Tabs.tsx
packages/cyberstorm/src/index.ts

@thunderstore/cyberstorm: add NewTabs
Add an improved version Tabs component. The old Tabs component is
retained for now to avoid scope creep. Ideally eventually all of the
old components will be replaced, the old implementation removed and
NewTabs renamed to Tabs.
The main motivation for the new implementation is an usecase from
PackageDetailLayout. Dapper will initally load only content for the
default tab. Additionally it will load flags defining whether other
tabs have content. E.g. if the changelog tab has no content, the tab is
disabled. If changelog exists, it's loaded with a separate Dapper call.
Additional improvements include:
- Moving away from "children as props" approach
- Ease of use when developer doesn't have to provide the tab buttons
and contents separately
- Ease of use …

@thunderstore/cyberstorm: add NewTabs

---

packages/dapper-fake/src/fakers/package.ts
packages/dapper/src/types/package.ts

- Add has_changelog fields which will be used to determine whether the
corresponding tab should be disabled or not
- Remove versions, since this data will be fetched with a separate
Dapper call when user navigates to related tab. has_versions field is
not needed since package always has at least one version
- Add latest_version_number which will be needed for forming the package
install URL
Refs TS-1979

@thunderstore/dapper: refine Package interface

---

apps/cyberstorm-storybook/stories/components/MultiSelectSearch.stories.tsx
packages/cyberstorm/src/components/MultiSelectSearch/MultiSelectSearch.module.css
packages/cyberstorm/src/components/MultiSelectSearch/MultiSelectSearch.tsx
packages/cyberstorm/src/utils/type_guards.ts

Add MultiSelectSearch component

---

packages/cyberstorm/src/components/Dialog/Dialog.module.css
packages/cyberstorm/src/components/Header/Header.module.css

Fix an issue where; if something with z-index: auto
is in a dialog, its placed behind the dialog.

Fix z-index interaction between Header, Dialog and Dialog content

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageMetaItems/PackageMetaItems.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageTagList/PackageTagList.tsx
packages/cyberstorm/src/components/PackageCard/PackageCard.tsx
packages/cyberstorm/src/utils/utils.ts
packages/dapper-fake/src/fakers/package.ts
packages/dapper-fake/src/index.ts
packages/dapper-ts/src/__tests__/index.ts
packages/dapper-ts/src/index.ts
packages/dapper/src/dapper.ts
packages/dapper/src/types/methods.ts
packages/dapper/src/types/package.ts

@thunderstore/dapper rename PackagePreview to PackageListing
The naming is more accurate, since the included data contains community
specific information. Packages exist separately from the communities,
so we might eventually want to fetch just package data.
Refs TS-1980
@thunderstore/dapper rename Package to PackageListingDetails
The naming is more accurate, since the included data contains community
specific information. Packages exist separately from the communities,
so we might eventually want to fetch just package data.
Refs TS-1980
@thunderstore/dapper: rename getPackage to getPackageListingDetails
The naming is more accurate, since the included data contains community
specific information. Packages exist separately from the communities,
so we might eventually want to fetch just …

@thunderstore/dapper: rename method and interfaces

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx

The component now accepts a list of dependencies as a prop instead of
fetching the data itself with Dapper. This was changed because it made
more sense to fetch the dependencies with the same request as the rest
of PackageDetailLayout's contents (excluding tabs).
Also includes some generic cleanup.
Refs TS-1980

@thunderstore/cyberstorm: change PackageDependencyList props

---

packages/dapper-fake/src/fakers/package.ts
packages/dapper-fake/src/index.ts
packages/dapper-ts/src/__tests__/index.ts
packages/dapper-ts/src/index.ts
packages/dapper/src/dapper.ts
packages/dapper/src/types/methods.ts

The method is not needed, the data is received in the
getPackageListingDetails response.
Refs TS-1980

@thunderstore/dapper: remove getDependencies

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/utils/utils.ts
packages/dapper-fake/src/fakers/package.ts
packages/dapper-ts/src/methods/packageListings.ts
packages/dapper/src/types/package.ts

It's better to manage the URLs in the backend so it'll be easier to
change them in the future if we need to. Also reduces duplicate code
in the different clients.
Refs TS-1980

Use download/install URLs generated by the backend

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageVersions/PackageVersions.module.css
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageVersions/PackageVersions.tsx

- Receive package info as props and use it to fetch the data via Dapper
instead of using dummy data
- Add suspense around the component on the layout
- Remove unused CSS
- Clean up the helper components
- Use links instead of buttons for download and install actions
Refs TS-2002

@thunderstore/cyberstorm: improve PackageVersions

---

apps/cyberstorm-storybook/stories/components/MultiSelectSearch.stories.tsx

It appears that the typing of the component's props have changed but
the story was not updated. Consequently this broke the CI pipeline.
Hopefully the unknown type can be removed from the props once the work
on the component continues, which in turn would allow better typing for
this story.
Refs no ticket

@thunderstore/cyberstorm-storybook: fix MultiSelectSearch story

---

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.module.css
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper-ts/src/methods/packageListings.ts
packages/dapper/src/types/package.ts

@thunderstore/dapper: add dependency_count to PackageListingDetails
To avoid bloat on packages with a large number of dependencies, backend
initially returns up to 4 items. More can be loaded later if user so
wishes (method not implemented yet).
Total number of dependencies is returned in a separate field so UI can
indicate that the shown list of dependencies is incomplete.
Refs TS-2012
@thunderstore/cyberstorm: change PackageDependencyList functionality
- Show only four items (this is a fail-safe, Dapper should return only
four items anyway to avoid slowing down the page load)
- Show description if there's no dependencies, or if there are more
dependencies than can be shown on the card component
- Show "show more" link only if there's actually more than the four
visible dependencies
- …

@thunderstore/dapper: add dependency_count to PackageListingDetails

---

packages/cyberstorm/src/components/ImageWithFallback/ImageWithFallback.module.css
packages/cyberstorm/src/components/ImageWithFallback/ImageWithFallback.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyDialog/PackageDependencyDialog.module.css
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyDialog/PackageDependencyDialog.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.module.css
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.tsx
packages/dapper-fake/src/fakers/package.ts
packages/dapper-ts/src/methods/packageListings.ts
packages/dapper/src/types/package.ts

@thunderstore/dapper: support deactivated dependencies
Since deactivated dependencies are still required to use a mod, backend
will return them with the rest of the dependencies from now on. New
field is_active is returned with the data. Since the reason for
deactivation might be a gross icon or description text, null and a
placeholder text is returned instead.
Refs TS-2013
@thunderstore/cyberstorm: support deactivated dependencies
To accommodate for the fact that deactivated dependencies will return
a null instead of icon URL:
- Use ImageWithFallback component instead of img element
- Add support for package icon type to ImageWithFallback
- Add support for square images to ImageWithFallback
These changes were done since it's the minimum required to prevent the
build from breaking. The …

@thunderstore/dapper: support deactivated dependencies

---

packages/cyberstorm/src/components/Layout/CommunityProfileLayout/CommunityProfileLayout.tsx
packages/cyberstorm/src/components/Layout/HomeLayout/HomeLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDependantsLayout/PackageDependantsLayout.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageChangeLog/PackageChangeLog.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageReadme/PackageReadme.tsx
packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageVersions/PackageVersions.tsx
packages/cyberstorm/src/components/Layout/TeamProfileLayout/TeamProfileLayout.tsx
packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamDetails/TeamDetails.tsx
packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamMembers/TeamMembers.tsx
packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamServiceAccounts/TeamServiceAccounts.tsx

I'm not 100% certain I understand everything that's going on here, but it seemed components that call useDapper and don't have "use client" defined work nicely when building the project or when accessed in the browser with a direct url (server-side rendered?). But then they break when accessed by navigation from another page (client-side rendered?).
Error messages shown on server's logs show that when rehydrating(?) the page neither ServerDapper nor ClientDapper context provided the Dapper for these pages. Also it seemed that the errors were logged before the actual navigation event, but this might be due NextJs prefetching the content. The error didn't affect components that fetched content with Dapper without navigation (e.g. changelog tab on package listing page).
Or I might be …

Fix issues with rehydration of components that use Dapper

---

packages/cyberstorm/src/components/Button/Button.tsx
packages/cyberstorm/src/components/Footer/Footer.module.css
packages/cyberstorm/src/components/Footer/Footer.tsx
packages/cyberstorm/src/components/Header/Header.tsx

Internalize "Button to Anchor" logic into Button component
Sometimes Button might be used as a link and in these cases we
want to have Button component as <a> instead of div wrapped with <a>
Fix "Get Manager" buttons
Remove anchor wrappers
Fix styles to be up to specs

Internalize "Button to Anchor" logic into Button component

---

apps/cyberstorm-remix/cyberstorm/navigation/DevelopersDropDown.tsx
packages/cyberstorm/src/components/Footer/Footer.tsx

Order items in developers menu by importance

---

apps/cyberstorm-storybook/stories/newComponents/DropDown.stories.tsx
packages/cyberstorm-theme/src/components/DropDown/DropDown.css
packages/cyberstorm/src/newComponents/DropDown/DropDown.css
packages/cyberstorm/src/newComponents/DropDown/DropDown.tsx

So that for example links are the full width of the dropdown menu

Remove DropdownItem wrapping

---

apps/cyberstorm-remix/cyberstorm/utils/LinkLibrary.tsx

So that it actually takes users to the old page instead of not finding
the new unreleased version yet

Force document reload on all Remix links

---

apps/cyberstorm-remix/app/commonComponents/PackageSearch/PackageSearch.tsx
apps/cyberstorm-remix/app/p/packageListing.tsx
packages/cyberstorm-forms/src/actions/PackageLikeAction.tsx
packages/cyberstorm-forms/src/useFormToaster.ts
packages/ts-api-react-actions/src/ApiAction.tsx
packages/ts-api-react-actions/src/index.ts
packages/ts-api-react-actions/src/schema.ts
packages/ts-api-react-actions/src/useApiAction.ts

In the last tag the ability to like packages was added to PackageSearch.
This caused React issues because there were different amount of hooks
between re-renders. The solution here is to generate the hook ones and
then just change the input data to that hook.
This solution though warranted some changes to how ApiAction accepts
data. Corresponding changes are done to the PackageLikeAction.
On the same go this commit improves success and error message displaying
via toasts. The changes to useFormToaster are only done to
PackageLikeAction at this moment, but considering all the other actions
and forms are un-used right now, the same changes to other "action" and
"form" functions can be done, when they are taken into use.
Additionally UseApiAction now has return data types.

Improve ApiAction and fix hook mismatch in PackageSearch re-renders

---

packages/ts-api-react/src/SessionContext.tsx

When getting the current user with getCurrentUser the only case when 401
is returned is, when the sessionid cookie / the session at Djangos end
is stale or invalid. Remove it at the same time when Nimbus session is
removed.

Remove sessionid cookie when it's invalid

---

apps/cyberstorm-remix/app/commonComponents/CopyButton/CopyButton.css
apps/cyberstorm-remix/app/commonComponents/CopyButton/CopyButton.tsx

If the copy action is tried in a non-safe domain, it wont just work. We
don't need to check for it.

Remove isSupported check from CopyButton as it serves no purpose

---

apps/cyberstorm-remix/cyberstorm/utils/LinkLibrary.tsx

Please see the comment in commited code.

Correct link behaviour in subdomainless Remix deployment
