thunderstore-io/thunderstore-ui

.prettierrc
Ran on #8 to validate that it matches exactly. Should've done that to start 😬
=> chore(prettier): reset to entirely default config

thunderstore-components/src/components/FileUpload.tsx, thunderstore-components/src/components/PackageUpload.tsx, thunderstore-components/src/components/StickyFooter.tsx
- Change `FileUpload` and `StickyFooter` to `gray.700`
- Add loading bar to decompressing message in `PackageUpload`
=> Initial updates to PackageUpload and related components

apps/nextjs/package.json, apps/storybook/package.json, packages/components/package.json, packages/components/src/components/PackageActions.tsx, yarn.lock
Commit 3c0e8e4 introduced a temporary version of @chakra-ui/react
which partially fixed type-related issues. The newest release includes
these fixes, and also fixes the problems with typing variant prop, so
related temporary fixes can now be removed from codebase.
However, this introduces a new issue, but it's such a minor one that
updating now seems reasonable:
https://github.com/chakra-ui/chakra-ui/issues/5453
=> Update @chakra-ui/react to 1.8.0

.github/workflows/test.yml
Enable automatic deployment of the dev environment whenever a new commit
is made to master.
=> Automatically deploy dev environment from master

apps/nextjs/components/TopBar.tsx, packages/components/src/customStyles/Button.ts, packages/components/src/customStyles/Link.ts
* Toggle login/logout functionality
* Toggle features restricted to authenticated users
Refs TS-230, TS-461
=> @thunderstore/nextjs: adapt TopBar content based on auth status

packages/components/src/components/CommunityCard.tsx, packages/components/src/components/PackageCard.tsx, packages/components/src/components/PackageHeader.tsx, packages/components/src/components/PackageSearch.tsx, packages/components/src/components/TopBar.tsx
Prefer CSS over adding superfluous divs for presentation's sake.
Refs TS-548
=> @thunderstore/components: yeet Chakra's spacer

apps/sertra/Dockerfile, apps/sertra/README.md, package.json
Based on the Dockerfile for @thunderstore/nextjs.
Refs TS-504
=> @thunderstore/sertra: add Dockerfile

apps/sertra/api/hooks.ts, apps/sertra/components/ServerDetail.module.css, apps/sertra/components/ServerList.tsx, apps/sertra/components/listingAttributes.tsx, apps/sertra/pages/server/[id].tsx
Full Detail page including data fetching from API
API is missing some data for mods,
but those have been marked TODO
refs TS-520
=> ServerListing Detail page

apps/sertra/components/ServerDetail.module.css, apps/sertra/styles/globals.css
Mostly changes how the CSS looks like. Shouldn't affect that much how
the actual page looks like. Some (sub)pixel level changes did occur to
fonts, but these steps should be towards the Figma design, so they
should be ok
=> @thunderstore/sertra: CSS cleanup

apps/sertra/.gitignore, apps/sertra/components/mod-selector/list.tsx, apps/sertra/components/mod-selector/search.tsx, apps/sertra/pages/index.tsx
added some keyboard controls and fixed some other issues
=> add  keyboard controls and fix form

apps/sertra/package.json, apps/sertra/pages/create.tsx, yarn.lock
Server listings can now be added
=> Add API integration to Server Submit

apps/sertra/pages/_document.tsx, apps/sertra/pages/index.tsx
create new _document.tsx file
move head index to _document file except title remains.
TS-1079
=> Move head element _document file

.github/workflows/storybook-chromatic.yml
Configure the Chromatic GitHub workflow to also run for the Cyberstorm UI project.
=> Enable chromatic for cyberstorm UI

apps/cyberstorm-storybook/public/css/globals.css, packages/cyberstorm/src/components/PackageCard.tsx, packages/cyberstorm/src/components/componentStyles/PackageCard.module.css, packages/cyberstorm/src/components/componentStyles/PackageFlag.module.css
Add PackageFlag to PackageCard
=> Add PackageFlag to PackageCard

apps/cyberstorm-storybook/.storybook/preview.js, apps/cyberstorm-storybook/LinkLibrary.tsx, packages/cyberstorm/src/components/LinkingProvider.tsx, packages/cyberstorm/src/components/Links.tsx, packages/cyberstorm/src/index.ts
Add LinkingProvider to Cyberstorm from the "old new" frontend
refs TS-1394
=> Add LinkingProvider to Cyberstorm

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx, packages/cyberstorm/src/components/MetaInfoItem/MetaInfoItem.module.css, packages/cyberstorm/src/components/MetaInfoItemList/MetaInfoItemList.module.css, packages/cyberstorm/src/components/MetaInfoItemList/MetaInfoItemList.tsx
refs https://app.clickup.com/t/20413243/TS-1595
=> Cyberstorm metainfoitemlist

packages/cyberstorm-styles/src/styles/globals.css, packages/cyberstorm/src/components/Layout/Developers/MarkdownPreview/MarkdownPreviewLayout.module.css, packages/cyberstorm/src/components/Layout/Developers/MarkdownPreview/MarkdownPreviewLayout.tsx, packages/cyberstorm/src/components/Markdown/Markdown.tsx, packages/cyberstorm/src/components/TextAreaInput/TextAreaInput.module.css, packages/cyberstorm/src/components/TextAreaInput/TextAreaInput.tsx, packages/cyberstorm/src/index.ts
Copy and paste the old implementation of markdown preview from the "old new UI" into cyberstorm
Add TextAreaInput component
Fix some stylings and use correct components in MarkdownPreviewLayout
=> Additions towards Markdown Preview page

apps/cyberstorm-nextjs/app/healthz/route.ts
Add a /healthz endpoint for monitoring the service status.
No refs
=> CS: Add /healthz endpoint

apps/cyberstorm-nextjs/.env.development, apps/cyberstorm-nextjs/app/layout.tsx, apps/cyberstorm-nextjs/app/page.tsx, packages/cyberstorm/src/components/DataTable/DataTable.tsx, packages/cyberstorm/src/components/Header/Header.tsx, packages/cyberstorm/src/components/Layout/Developers/MarkdownPreview/MarkdownPreviewLayout.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageVersions/PackageVersions.tsx, packages/dapper/src/cyberstormMethods/communities.ts, packages/dapper/src/cyberstormMethods/community.ts, packages/dapper/src/cyberstormSchemas/community.ts, packages/dapper/src/dapper.ts, packages/dapper/src/methods/communityPackageList.ts, packages/dapper/src/methods/frontpage.ts, packages/dapper/src/methods/package.ts, packages/dapper/src/singleton.ts
This PR does not yet enable any new functionality, but it does include some required cleanup and would make sense to merge as not to let the amount of pending changes grow too much.
=> Dapper implementation part 1

packages/cyberstorm/src/dummyData/generate.ts
Replace usage of deprecated faker functions with non-deprecated equivalents.
=> CS: Update deprecated faker usage

apps/cyberstorm-storybook/stories/components/Alert.stories.tsx, packages/cyberstorm-styles/src/styles/theme.css, packages/cyberstorm/src/components/Alert/Alert.module.css, packages/cyberstorm/src/components/Alert/Alert.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageManagementForm/PackageManagementForm.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageTeamMemberList/PackageTeamMemberList.tsx, packages/cyberstorm/src/components/Layout/Settings/Account/Account.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamList/TeamList.module.css, packages/cyberstorm/src/components/Layout/Teams/TeamList/TeamList.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamLeaveAndDisband/TeamLeaveAndDisband.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamServiceAccounts/ServiceAccountList/ServiceAccountList.module.css, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamServiceAccounts/ServiceAccountList/ServiceAccountList.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamServiceAccounts/TeamServiceAccounts.tsx, packages/cyberstorm/src/index.ts
refs https://app.clickup.com/t/20413243/TS-1694
=> Cyberstorm alert

apps/cyberstorm-storybook/stories/components/Switch.stories.tsx, packages/cyberstorm-styles/src/styles/globals.css, packages/cyberstorm/package.json, packages/cyberstorm/src/components/Layout/Settings/Connections/Connections.tsx, packages/cyberstorm/src/components/Switch/Switch.module.css, packages/cyberstorm/src/components/Switch/Switch.tsx, packages/cyberstorm/src/index.ts, yarn.lock
Add usage in User settings connections
refs TS-1693
=> Add Switch component into Cyberstorm

packages/cyberstorm/src/components/Layout/PackageListings/PackageListings.module.css
=> Use auto-fill instead of auto-fit in pkg list grid

packages/dapper/README.md
=> @thunderstore/dapper: update README to match recent refactoring

packages/cyberstorm/src/components/CollapsibleText/CollapsibleText.module.css, packages/cyberstorm/src/components/CollapsibleText/CollapsibleText.tsx, packages/cyberstorm/src/components/Layout/BaseLayout/PageHeader/PageHeader.module.css
refs [TS-1809](https://app.clickup.com/t/20413243/TS-1809)
=> fix description truncate

apps/cyberstorm-storybook/stories/components/Switch.stories.tsx
refs [TS-1816](https://app.clickup.com/t/20413243/TS-1816)
=> Fix disable prop and clean up components story

packages/cyberstorm/src/components/Tabs/Tabs.tsx, packages/cyberstorm/src/components/Tabs/TabsButton.tsx
=> Fix error when switching tabs

apps/cyberstorm-nextjs/.env.development, apps/cyberstorm-nextjs/app/login/page.tsx, apps/cyberstorm-nextjs/middleware.ts, apps/cyberstorm-nextjs/package.json, apps/cyberstorm-nextjs/utils/auth.ts, apps/cyberstorm-nextjs/utils/typeChecks.ts, apps/cyberstorm-storybook/stories/layouts/BetaLoginLayout.stories.tsx, packages/cyberstorm/src/components/Layout/LoginLayout/BetaLoginLayout.module.css, packages/cyberstorm/src/components/Layout/LoginLayout/BetaLoginLayout.tsx, yarn.lock
Add minimal authentication to Cyberstorm
That is coupled with old sites Django sessions
Add auth and redirection of unauthorized requests to "premium" page
into the middleware of nextjs
Add .env variables for disabling auth in development
Add .env variable for auth encryption secret
refs TS-1810
=> Add authentication to Cyberstorm

apps/cyberstorm-nextjs/middleware.ts
=> Add /healthz to auth exceptions

apps/cyberstorm-nextjs/app/page.tsx, apps/cyberstorm-nextjs/middleware.ts, apps/cyberstorm-nextjs/utils/LinkLibrary.tsx, packages/cyberstorm/src/components/Footer/Footer.tsx, packages/cyberstorm/src/components/Header/Header.tsx
Change links to landing page to be to community list view
Redirect /communities to / when enabled
refs TS-1828
=> Change /communities to be the landing page

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageChangeLog/PackageChangeLog.module.css
=> Remove height from changelog separator

packages/cyberstorm/src/components/Button/Button.module.css, packages/cyberstorm/src/components/Button/Button.tsx, packages/cyberstorm/src/components/Button/ButtonIcon.tsx, packages/cyberstorm/src/components/CodeInput/CodeInput.tsx, packages/cyberstorm/src/components/Layout/Developers/ManifestValidator/ManifestValidatorLayout.module.css, packages/cyberstorm/src/components/Layout/Developers/ManifestValidator/ManifestValidatorLayout.tsx, packages/cyberstorm/src/components/Layout/Developers/MarkdownPreview/MarkdownPreviewLayout.tsx, packages/cyberstorm/src/components/MenuItem/MenuItem.module.css, packages/cyberstorm/src/components/MenuItem/MenuItemLabel.tsx, packages/cyberstorm/src/components/Select/Select.module.css, packages/cyberstorm/src/components/Select/Select.tsx, packages/cyberstorm/src/components/ValidationBar/ValidationBar.module.css, packages/cyberstorm/src/components/ValidationBar/ValidationBar.tsx, packages/cyberstorm/src/index.ts, packages/cyberstorm/src/utils/type_guards.ts
Implements styles from Figma
Basic TS API fetching logic
Some minor fixes to other component styles needed by manifest validator
refs TS-1727
=> Manifest Validator page improvements

packages/cyberstorm/src/components/Footer/Footer.tsx
So that there isn't a p element with div inside
refs -
=> Change p element in footer to div

.eslintrc.json, apps/cyberstorm-storybook/stories/components/Switch.stories.tsx, packages/cyberstorm/src/components/Switch/Switch.tsx
[Refs TS-1840](https://app.clickup.com/t/20413243/TS-1840)
=> Switch component touchable label element

packages/cyberstorm/src/components/FilterItemList/FilterItem/FilterItem.module.css, packages/cyberstorm/src/components/FilterItemList/FilterItem/FilterItem.tsx, packages/cyberstorm/src/components/FilterItemList/FilterItemList.module.css, packages/cyberstorm/src/components/FilterItemList/FilterItemList.tsx
=> Fix FilterItem styles

packages/cyberstorm/src/components/Footer/Footer.module.css, packages/cyberstorm/src/components/Layout/Developers/PackageFormatDocs/PackageFormatDocsLayout.tsx, packages/cyberstorm/src/components/Table/Table.module.css
Fix footer image staying too big
Fix PackageFormatDocs tables being squished
refs TS-1857
=> Mobile responsivity improvements

packages/cyberstorm/src/components/Button/Button.module.css
[Refs TS-1851](https://app.clickup.com/t/20413243/TS-1851)
=> fix buttons to be non-selectable

apps/cyberstorm-storybook/stories/components/Button.stories.tsx, packages/cyberstorm/src/components/Button/Button.tsx, packages/cyberstorm/src/components/Header/Header.tsx, packages/cyberstorm/src/components/Layout/LoginLayout/LoginForm/LoginForm.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx, packages/dapper/src/context.tsx
[Refs TS-1788](https://app.clickup.com/t/20413243/TS-1788)
=> add tooltip to button component

packages/cyberstorm/src/components/Button/Button.module.css, packages/cyberstorm/src/components/Footer/Footer.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamDetails/TeamDetails.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamLeaveAndDisband/TeamLeaveAndDisband.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamMembers/TeamMemberList.tsx, packages/cyberstorm/src/components/Layout/Teams/TeamSettings/TeamServiceAccounts/ServiceAccountList/ServiceAccountListItem.tsx
=> Minor UI style changes

packages/cyberstorm/src/components/Footer/Footer.module.css, packages/cyberstorm/src/components/Footer/Footer.tsx
[Refs Footer - Copyright text is wrong](https://app.clickup.com/t/20413243/TS-1874)
=> Cyberstorm copyright

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageTagList/PackageTagList.tsx, packages/cyberstorm/src/components/PackageCard/PackageCard.tsx, packages/cyberstorm/src/utils/utils.ts
Replace bankersRound with appropriate rounding methods Add formatFileSize for formatting file sizes correctly
refs #887
=> Improve rounding and formatting with package data

packages/cyberstorm/src/components/Footer/Footer.tsx
=> Remove ? from Footer open source help request link

apps/cyberstorm-storybook/.storybook/main.js
[Refs TS-1874 - Storybook - There are 2 "cyberstorm" folders, remove one. Don't remove the contents.](https://app.clickup.com/t/20413243/TS-1874)
=> delete extra folder layer

packages/cyberstorm-styles/src/styles/globals.css, packages/cyberstorm/src/components/Header/Header.module.css, packages/cyberstorm/src/components/Layout/BaseLayout/BaseLayout.module.css, packages/cyberstorm/src/components/NewTabs/Tabs.module.css, packages/cyberstorm/src/components/PackageSearch/PackageSearch.module.css, packages/cyberstorm/src/components/WrapperCard/WrapperCard.module.css
NewTabs bottom border to be full width
Make package listings pages filter sidebar sticky
Fix WrapperCard padding
refs -
=> Minor but big UI effects

packages/cyberstorm/src/components/Dialog/Dialog.tsx
Remove defaultOpen prop since it was not used anywhere
Add open and onOpenChange to increase controllability of Dialog
=> Improve Dialog open state control

packages/cyberstorm-forms/src/components/FormSelect.module.css, packages/cyberstorm-forms/src/components/FormSelect.tsx, packages/cyberstorm/package.json, yarn.lock
This component contains a temporary TempSelect component
that will be used until CS Select component is refactored
to work with RHF
refs TS-2001
=> Add FormSelect component

packages/dapper-ts/src/__tests__/index.ts, packages/dapper-ts/src/index.ts, packages/dapper-ts/src/methods/packageListings.ts, packages/dapper-ts/src/methods/team.ts
Return information required to render (most of) PackageDetailLayout.
Refs TS-1980
=> @thunderstore/dapper-ts: add getPackageListingDetails

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyDialog/PackageDependencyDialog.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDependencyList/PackageDependencyList.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx, packages/cyberstorm/src/components/PackageCard/PackageCard.tsx, packages/dapper-fake/src/fakers/package.ts, packages/dapper-ts/src/methods/packageListings.ts, packages/dapper/src/types/package.ts
@thunderstore/dapper: packages are guaranteed to have an icon image
Refs TS-1999
@thunderstore/cyberstorm: packages are guaranteed to have an icon image
Refs TS-1999
=> @thunderstore/dapper: packages are guaranteed to have an icon image

packages/dapper-ts/src/__tests__/index.ts, packages/dapper-ts/src/index.ts, packages/dapper-ts/src/methods/package.ts
=> @thunderstore/dapper-ts: add getPackageChangelog and getPackageReadme

packages/dapper-fake/src/fakers/markup.ts, packages/dapper-fake/src/index.ts, packages/dapper/src/dapper.ts, packages/dapper/src/types/methods.ts, packages/dapper/src/types/shared.ts
The methods will return safe HTML which can be injected into the
site.
Refs TS-2000
=> @thunderstore/dapper: add getPackageChangelog and getPackageReadme

packages/thunderstore-api/src/fetch/__tests__/packageVersions.ts, packages/thunderstore-api/src/fetch/packageVersions.ts, packages/thunderstore-api/src/index.ts
Fetches a list of activa package versions for given package.
Refs TS-2002
=> @thunderstore/thunderstore-api: add getPackageVersions

packages/dapper-ts/src/__tests__/index.ts, packages/dapper-ts/src/index.ts, packages/dapper-ts/src/methods/package.ts
=> @thunderstore/dapper-ts: add getPackageVersions

packages/dapper-fake/src/fakers/package.ts, packages/dapper-fake/src/index.ts
=> @thunderstore/dapper-fake: add getPackageVersions

packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx
=> @thunderstore/cyberstorm: disable changelog tab if package has none

packages/dapper-ts/src/__tests__/index.ts, packages/thunderstore-api/src/fetch/__tests__/community.ts, packages/thunderstore-api/src/fetch/__tests__/communityList.ts, packages/thunderstore-api/src/fetch/__tests__/defaultConfig.ts, packages/thunderstore-api/src/fetch/__tests__/packageChangelog.ts, packages/thunderstore-api/src/fetch/__tests__/packageListingDetails.ts, packages/thunderstore-api/src/fetch/__tests__/packageReadme.ts, packages/thunderstore-api/src/fetch/communityPackageListings.ts, packages/thunderstore-api/src/fetch/namespacePackageListings.ts, packages/thunderstore-api/src/fetch/packageChangelog.ts, packages/thunderstore-api/src/fetch/packageDependantsListings.ts, packages/thunderstore-api/src/fetch/packageListingDetails.ts, packages/thunderstore-api/src/fetch/packageReadme.ts, packages/thunderstore-api/src/fetch/packageVersions.ts, packages/thunderstore-api/src/fetch/teamCreate.ts, packages/thunderstore-api/src/fetch/teamMembers.ts, packages/thunderstore-api/src/fetch/teamServiceAccounts.ts
API URLs were changed on the backend, bring the API lib up-to-date.
Refs TS-2008
=> @thunderstore/thunderstore: update API URLs

packages/cyberstorm/src/components/CommunityCard/CommunityCardSkeleton.module.css, packages/cyberstorm/src/components/CommunityCard/CommunityCardSkeleton.tsx, packages/cyberstorm/src/components/Layout/CommunityListLayout/CommunityListLayout.tsx, packages/cyberstorm/src/components/Layout/CommunityListLayout/CommunityListSkeleton.tsx, packages/cyberstorm/src/components/Layout/CommunityListLayout/Loading.tsx
=> Add CommunityList skeleton component

packages/cyberstorm/src/components/Header/Header.module.css
Make sure page Header stays on top of page contents effects, etc
=> Make sure page Header stays on top

packages/cyberstorm/src/components/AntiResult/AntiResult.module.css, packages/cyberstorm/src/components/AntiResult/AntiResult.tsx, packages/cyberstorm/src/components/AntiResult/AntiResultIcon.tsx, packages/cyberstorm/src/components/AntiResult/AntiResultMessage.tsx, packages/cyberstorm/src/components/AntiResult/AntiResultTitle.tsx, packages/cyberstorm/src/components/AntiResult/index.ts, packages/cyberstorm/src/components/Layout/CommunityListLayout/CommunityList.module.css, packages/cyberstorm/src/components/Layout/CommunityListLayout/CommunityList.tsx, packages/cyberstorm/src/index.ts
Add AntiResult component set
Add AntiResult to communities list
=> Add AntiResult component set

packages/cyberstorm/src/components/Header/Header.module.css
This will be revisited once modals are worked on
=> Raise Header z-index

packages/cyberstorm/src/components/BreadCrumbs/BreadCrumbs.module.css, packages/cyberstorm/src/components/BreadCrumbs/BreadCrumbs.tsx, packages/cyberstorm/src/components/Footer/Footer.module.css, packages/cyberstorm/src/components/Footer/Footer.tsx, packages/cyberstorm/src/components/Header/Header.module.css, packages/cyberstorm/src/components/Icon/Icon.module.css, packages/cyberstorm/src/components/MenuItem/MenuItem.module.css, packages/cyberstorm/src/components/MetaItem/MetaItem.module.css
=> Many smaller fix towards /communities

apps/cyberstorm-nextjs/app/RootLayout.module.css, apps/cyberstorm-nextjs/app/c/[community]/(community)/@community/@communityCard/page.tsx, packages/cyberstorm/src/components/CommunityCard/CommunityCard.tsx, packages/cyberstorm/src/components/Header/Header.tsx, packages/cyberstorm/src/components/Layout/CommunityProfileLayout/CommunityProfileLayout.tsx, packages/cyberstorm/src/components/Layout/PackageDetailLayout/PackageDetailLayout.tsx, packages/cyberstorm/src/components/MetaItem/MetaItem.module.css, packages/cyberstorm/src/components/MetaItem/MetaItem.tsx, packages/dapper-fake/src/fakers/community.ts, packages/dapper-ts/src/methods/communities.ts, packages/dapper/src/types/community.ts
=> Add cover_image_url to Dapper and use it

apps/cyberstorm-nextjs/app/RootLayout.module.css, apps/cyberstorm-nextjs/config.ts, apps/cyberstorm-nextjs/dapper/client.tsx, apps/cyberstorm-nextjs/dapper/server.tsx, apps/cyberstorm-nextjs/utils/provider.tsx
NextJS wants to bundle constants and not change them
Remove constant assignment from config to ensure it's
being evaluated on runtime
refs -
=> Fix issue configs dev env var assignment

apps/cyberstorm-nextjs/.env.development, apps/cyberstorm-nextjs/Dockerfile.development, docker-compose.development.yml, nginx/conf.d/default.conf
Just something the people who know, can use
Guides/improvements coming later
=> Add "working" docker compose configs

ManualUXTests.md
To
1. Ensure we stay in sync with users UX needs.
2. Users can check if a feature is working as intended
refs -
=> Add ManualUXTests

packages/cyberstorm/src/components/CommunityCard/CommunityCard.tsx
- Add title for image anchor
- Remove title from label anchor parent
Refs TS-2124
=> Fix community card anchor accesibility

apps/cyberstorm-remix/app/commonComponents/Footer/Footer.css, apps/cyberstorm-remix/app/commonComponents/PackageSearch/CategoryTagCloud/CategoryTagCloud.tsx, apps/cyberstorm-remix/app/commonComponents/PackageSearch/FilterMenus/CategoryMenu.tsx, apps/cyberstorm-remix/app/commonComponents/PackageSearch/FilterMenus/FilterMenu.module.css, apps/cyberstorm-remix/app/commonComponents/PackageSearch/FilterMenus/OthersMenu.tsx, apps/cyberstorm-remix/app/commonComponents/PackageSearch/FilterMenus/SectionMenu.tsx, apps/cyberstorm-remix/app/commonComponents/PackageSearch/PackageSearch.module.css, apps/cyberstorm-remix/app/commonComponents/PackageSearch/PackageSearch.tsx, apps/cyberstorm-remix/app/styles/layout.css, packages/cyberstorm/src/newComponents/Card/CardPackage/CardPackage.css, packages/cyberstorm/src/newComponents/Card/CardPackage/CardPackage.tsx, packages/cyberstorm/src/newComponents/Tag/Tag.css
Set the footer width to a variable
CardPackage style update
Add dividers and heading to filter sidebar
Add keyword search as a removable search param  to the tag cloud
=> PackageSearch and Footer changes

apps/cyberstorm-remix/cyberstorm/navigation/DesktopLoginPopover.tsx, apps/cyberstorm-remix/cyberstorm/navigation/DevelopersDropDown.tsx, apps/cyberstorm-remix/cyberstorm/navigation/Navigation.module.css, apps/cyberstorm-remix/cyberstorm/navigation/Navigation.tsx, packages/cyberstorm-theme/src/components/DropDown/DropDown.css, packages/cyberstorm-theme/src/components/Select/Select.css, packages/cyberstorm-theme/src/components/Table/Table.css, packages/cyberstorm/src/newComponents/DropDown/DropDown.css, packages/cyberstorm/src/newComponents/Menu/Menu.tsx
Login popover modal styles
Navigation right side buttons
Fix/remove dropdown related bad css variables
=> Update Navigation styles

apps/cyberstorm-remix/app/communities/communities.tsx, apps/cyberstorm-remix/app/settings/teams/team/tabs/Members/Members.tsx, apps/cyberstorm-remix/app/settings/teams/team/tabs/ServiceAccounts/ServiceAccounts.tsx
Fix communities page classname
Remove unused classes
=> Fix communities page classname

apps/cyberstorm-remix/app/root.tsx, apps/cyberstorm-remix/app/tools/manifest-validator/manifestValidator.tsx, apps/cyberstorm-remix/vite.config.ts, packages/cyberstorm/src/components/Dialog/Dialog.module.css, packages/cyberstorm/src/components/MultiSelectSearch/MultiSelectSearch.module.css, packages/cyberstorm/src/components/SelectSearch/SelectSearch.module.css, packages/cyberstorm/src/components/TextAreaInput/TextAreaInput.module.css, packages/cyberstorm/src/components/TextInput/TextInput.module.css, packages/cyberstorm/src/newComponents/Select/Select.css
Enable developer tools pages
Fix few minor style issues
=> Enable developer tools pages

apps/cyberstorm-remix/app/commonComponents/Navigation/Navigation.tsx, apps/cyberstorm-remix/app/commonComponents/Navigation/NavigationWrapper.tsx, apps/cyberstorm-remix/app/root.tsx
These were linking to the remix site, when they should be linking to the Django side
=> Fix API Docs and logout links

apps/cyberstorm-remix/app/p/team/Team.tsx
=> Remove Team link for Team page

apps/cyberstorm-remix/app/p/packageListing.tsx, packages/cyberstorm/src/newComponents/Tag/Tag.tsx, packages/cyberstorm/src/primitiveComponents/Actionable/Actionable.tsx
This includes adding cyberstormLink mode to Tag component
=> Make category tags in package detail page clickable

apps/cyberstorm-remix/app/styles/layout.css
So that the "report ad" button is fully visible
=> Increase AdContainer gaps in layout

apps/cyberstorm-remix/app/commonComponents/PackageSearch/PackageSearch.tsx, apps/cyberstorm-remix/app/communities/communities.tsx, apps/cyberstorm-remix/app/root.tsx
But also add preventScrollReset to all setSearchParams calls
=> Enable ScrollRestoration

apps/cyberstorm-remix/app/commonComponents/PackageSearch/PackageSearch.tsx
Fix isssues when navigating backwards of forwards in the history stack
Add explanation of PackageSearch's logic and specs
Side note; Considering this whole logic mess is needed on other pages
too it should be considered if this implementation is peak or not
=> Fix PackageSearch navigation issues
